name: ITMO Matrix Autograding 2025

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc python3 git

      - name: Build matrix calculator
        run: |
          gcc main.c -std=c23 -lm -o matrix

      - name: Clone 2025 public tests
        run: |
          git clone https://github.com/se-c-cpp-prog/public-tests-2025.git

      - name: Run 2025 test suite
        run: |
          python3 public-tests-2025/main.py --program ./matrix --suite math
